// ===================================================================
// Daily Digest — Domain Knowledge Definitions
// 50+ domains across 8 categories with RSS feeds, colors, and icons.
// ===================================================================

export interface DomainDef {
    id: string;
    name: string;
    icon: string; // lucide icon name
    category: DomainCategory;
    color: string; // tailwind gradient classes
    accentColor: string; // single color for charts/badges
    rssFeeds: string[];
    searchKeywords: string[];
    description: string;
}

export type DomainCategory =
    | "academics"
    | "tech"
    | "career"
    | "sports"
    | "creative"
    | "lifestyle"
    | "popculture"
    | "studentlife";

export interface DomainCategoryDef {
    id: DomainCategory;
    label: string;
    icon: string;
    gradient: string;
}

export const DOMAIN_CATEGORIES: DomainCategoryDef[] = [
    { id: "academics", label: "Academics & Science", icon: "GraduationCap", gradient: "from-blue-500 to-indigo-600" },
    { id: "tech", label: "Tech & Engineering", icon: "Cpu", gradient: "from-cyan-500 to-teal-600" },
    { id: "career", label: "Career & Business", icon: "Briefcase", gradient: "from-amber-500 to-orange-600" },
    { id: "sports", label: "Sports & Fitness", icon: "Trophy", gradient: "from-emerald-500 to-green-600" },
    { id: "creative", label: "Creative Arts", icon: "Palette", gradient: "from-pink-500 to-rose-600" },
    { id: "lifestyle", label: "Lifestyle & Wellness", icon: "Heart", gradient: "from-violet-500 to-purple-600" },
    { id: "popculture", label: "Pop Culture", icon: "Flame", gradient: "from-red-500 to-orange-600" },
    { id: "studentlife", label: "Student Life", icon: "Backpack", gradient: "from-sky-500 to-blue-600" },
];

export const DOMAINS: DomainDef[] = [
    // ── Academics & Science ──────────────────────────────
    {
        id: "computer-science",
        name: "Computer Science",
        icon: "Monitor",
        category: "academics",
        color: "from-blue-500 to-cyan-500",
        accentColor: "#3b82f6",
        rssFeeds: [
            "https://news.ycombinator.com/rss",
            "https://feeds.feedburner.com/TheHackersNews",
        ],
        searchKeywords: ["algorithms", "data structures", "systems", "programming", "CS research"],
        description: "Algorithms, systems, programming paradigms",
    },
    {
        id: "mathematics",
        name: "Mathematics",
        icon: "Sigma",
        category: "academics",
        color: "from-indigo-500 to-blue-500",
        accentColor: "#6366f1",
        rssFeeds: [
            "https://www.quantamagazine.org/feed/",
        ],
        searchKeywords: ["mathematics", "proofs", "algebra", "calculus", "topology"],
        description: "Pure & applied mathematics, number theory",
    },
    {
        id: "physics",
        name: "Physics",
        icon: "Atom",
        category: "academics",
        color: "from-violet-500 to-indigo-500",
        accentColor: "#8b5cf6",
        rssFeeds: [
            "https://phys.org/rss-feed/",
        ],
        searchKeywords: ["quantum", "relativity", "particle physics", "astrophysics"],
        description: "Quantum mechanics, relativity, particle physics",
    },
    {
        id: "chemistry",
        name: "Chemistry",
        icon: "FlaskConical",
        category: "academics",
        color: "from-teal-500 to-emerald-500",
        accentColor: "#14b8a6",
        rssFeeds: [
            "https://phys.org/rss-feed/chemistry-news/",
        ],
        searchKeywords: ["organic chemistry", "biochemistry", "molecular", "periodic table"],
        description: "Organic, inorganic, analytical chemistry",
    },
    {
        id: "biology",
        name: "Biology",
        icon: "Dna",
        category: "academics",
        color: "from-green-500 to-emerald-500",
        accentColor: "#22c55e",
        rssFeeds: [
            "https://phys.org/rss-feed/biology-news/",
        ],
        searchKeywords: ["genetics", "evolution", "ecology", "cell biology", "microbiology"],
        description: "Genetics, evolution, ecology, cell biology",
    },
    {
        id: "medicine",
        name: "Medicine & Health",
        icon: "Stethoscope",
        category: "academics",
        color: "from-red-500 to-pink-500",
        accentColor: "#ef4444",
        rssFeeds: [
            "https://www.medscape.com/cx/rssfeeds/2701",
        ],
        searchKeywords: ["medicine", "clinical research", "healthcare", "public health"],
        description: "Clinical research, public health, medical breakthroughs",
    },
    {
        id: "psychology",
        name: "Psychology",
        icon: "Brain",
        category: "academics",
        color: "from-fuchsia-500 to-pink-500",
        accentColor: "#d946ef",
        rssFeeds: [
            "https://www.psychologytoday.com/intl/blog/feed",
        ],
        searchKeywords: ["cognitive science", "behavioral psychology", "neuroscience"],
        description: "Cognitive science, behavior, neuroscience",
    },
    {
        id: "economics",
        name: "Economics",
        icon: "TrendingUp",
        category: "academics",
        color: "from-amber-500 to-yellow-500",
        accentColor: "#f59e0b",
        rssFeeds: [
            "https://feeds.feedburner.com/economistbriefing",
        ],
        searchKeywords: ["macroeconomics", "microeconomics", "fiscal policy", "trade"],
        description: "Macro/micro economics, fiscal policy, markets",
    },
    {
        id: "political-science",
        name: "Political Science",
        icon: "Landmark",
        category: "academics",
        color: "from-slate-500 to-gray-500",
        accentColor: "#64748b",
        rssFeeds: [],
        searchKeywords: ["geopolitics", "democracy", "governance", "political theory"],
        description: "Geopolitics, governance, political theory",
    },
    {
        id: "philosophy",
        name: "Philosophy",
        icon: "Lightbulb",
        category: "academics",
        color: "from-yellow-500 to-amber-500",
        accentColor: "#eab308",
        rssFeeds: [],
        searchKeywords: ["ethics", "metaphysics", "logic", "existentialism"],
        description: "Ethics, logic, metaphysics, epistemology",
    },
    {
        id: "history",
        name: "History",
        icon: "Scroll",
        category: "academics",
        color: "from-stone-500 to-amber-600",
        accentColor: "#a8a29e",
        rssFeeds: [],
        searchKeywords: ["world history", "ancient civilizations", "modern history"],
        description: "Ancient civilizations, modern history, historiography",
    },
    {
        id: "literature",
        name: "Literature",
        icon: "BookOpen",
        category: "academics",
        color: "from-rose-500 to-red-500",
        accentColor: "#f43f5e",
        rssFeeds: [],
        searchKeywords: ["fiction", "poetry", "literary criticism", "world literature"],
        description: "Fiction, poetry, literary criticism",
    },
    {
        id: "environmental-science",
        name: "Environmental Science",
        icon: "Leaf",
        category: "academics",
        color: "from-lime-500 to-green-600",
        accentColor: "#84cc16",
        rssFeeds: [],
        searchKeywords: ["climate change", "sustainability", "ecology", "renewable energy"],
        description: "Climate, sustainability, renewable energy",
    },
    {
        id: "astronomy",
        name: "Astronomy",
        icon: "Telescope",
        category: "academics",
        color: "from-indigo-600 to-violet-600",
        accentColor: "#4f46e5",
        rssFeeds: [
            "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        ],
        searchKeywords: ["space", "NASA", "exoplanets", "cosmology", "telescopes"],
        description: "Space exploration, cosmology, exoplanets",
    },
    {
        id: "sociology",
        name: "Sociology",
        icon: "Users",
        category: "academics",
        color: "from-orange-400 to-red-400",
        accentColor: "#fb923c",
        rssFeeds: [],
        searchKeywords: ["social dynamics", "culture", "inequality", "urbanization"],
        description: "Social dynamics, culture, inequality",
    },
    {
        id: "linguistics",
        name: "Linguistics",
        icon: "Languages",
        category: "academics",
        color: "from-cyan-400 to-blue-400",
        accentColor: "#22d3ee",
        rssFeeds: [],
        searchKeywords: ["syntax", "semantics", "NLP", "phonetics", "language acquisition"],
        description: "Syntax, semantics, phonetics, NLP",
    },

    // ── Tech & Engineering ───────────────────────────────
    {
        id: "artificial-intelligence",
        name: "Artificial Intelligence",
        icon: "Bot",
        category: "tech",
        color: "from-cyan-500 to-blue-500",
        accentColor: "#06b6d4",
        rssFeeds: [
            "https://news.ycombinator.com/rss",
            "https://www.marktechpost.com/feed/",
        ],
        searchKeywords: ["AI", "machine learning", "deep learning", "LLMs", "neural networks"],
        description: "ML, deep learning, LLMs, neural networks",
    },
    {
        id: "web-development",
        name: "Web Development",
        icon: "Globe",
        category: "tech",
        color: "from-orange-500 to-red-500",
        accentColor: "#f97316",
        rssFeeds: [
            "https://dev.to/feed",
            "https://css-tricks.com/feed/",
        ],
        searchKeywords: ["React", "Next.js", "CSS", "JavaScript", "TypeScript", "frontend"],
        description: "React, Next.js, CSS, full-stack, web APIs",
    },
    {
        id: "mobile-dev",
        name: "Mobile Development",
        icon: "Smartphone",
        category: "tech",
        color: "from-green-500 to-teal-500",
        accentColor: "#10b981",
        rssFeeds: [],
        searchKeywords: ["iOS", "Android", "React Native", "Flutter", "Swift", "Kotlin"],
        description: "iOS, Android, React Native, Flutter",
    },
    {
        id: "cybersecurity",
        name: "Cybersecurity",
        icon: "Shield",
        category: "tech",
        color: "from-red-600 to-rose-600",
        accentColor: "#dc2626",
        rssFeeds: [
            "https://feeds.feedburner.com/TheHackersNews",
        ],
        searchKeywords: ["infosec", "pentesting", "CTF", "vulnerabilities", "zero-day"],
        description: "InfoSec, pentesting, CTF, vulnerabilities",
    },
    {
        id: "cloud-computing",
        name: "Cloud Computing",
        icon: "Cloud",
        category: "tech",
        color: "from-sky-500 to-blue-500",
        accentColor: "#0ea5e9",
        rssFeeds: [],
        searchKeywords: ["AWS", "Azure", "GCP", "serverless", "kubernetes", "docker"],
        description: "AWS, Azure, GCP, Kubernetes, serverless",
    },
    {
        id: "blockchain",
        name: "Blockchain & Web3",
        icon: "Link",
        category: "tech",
        color: "from-purple-600 to-indigo-600",
        accentColor: "#9333ea",
        rssFeeds: [],
        searchKeywords: ["crypto", "DeFi", "smart contracts", "Ethereum", "Web3"],
        description: "Crypto, DeFi, smart contracts, Web3",
    },
    {
        id: "robotics",
        name: "Robotics",
        icon: "Cog",
        category: "tech",
        color: "from-zinc-500 to-gray-500",
        accentColor: "#71717a",
        rssFeeds: [],
        searchKeywords: ["robotics", "automation", "drones", "autonomous vehicles"],
        description: "Automation, drones, autonomous systems",
    },
    {
        id: "iot",
        name: "IoT & Embedded",
        icon: "Wifi",
        category: "tech",
        color: "from-teal-500 to-cyan-500",
        accentColor: "#14b8a6",
        rssFeeds: [],
        searchKeywords: ["IoT", "Arduino", "Raspberry Pi", "embedded systems", "sensors"],
        description: "Arduino, Raspberry Pi, smart devices",
    },
    {
        id: "game-dev",
        name: "Game Development",
        icon: "Gamepad2",
        category: "tech",
        color: "from-violet-500 to-purple-500",
        accentColor: "#8b5cf6",
        rssFeeds: [],
        searchKeywords: ["Unity", "Unreal", "game design", "indie games", "Godot"],
        description: "Unity, Unreal, Godot, game design",
    },
    {
        id: "data-science",
        name: "Data Science",
        icon: "BarChart3",
        category: "tech",
        color: "from-emerald-500 to-teal-500",
        accentColor: "#10b981",
        rssFeeds: [],
        searchKeywords: ["pandas", "data analysis", "visualization", "statistics", "R"],
        description: "Data analysis, visualization, statistics",
    },
    {
        id: "devops",
        name: "DevOps & SRE",
        icon: "Container",
        category: "tech",
        color: "from-blue-600 to-indigo-600",
        accentColor: "#2563eb",
        rssFeeds: [],
        searchKeywords: ["CI/CD", "terraform", "ansible", "monitoring", "GitOps"],
        description: "CI/CD, terraform, monitoring, GitOps",
    },
    {
        id: "quantum-computing",
        name: "Quantum Computing",
        icon: "Zap",
        category: "tech",
        color: "from-fuchsia-600 to-violet-600",
        accentColor: "#c026d3",
        rssFeeds: [],
        searchKeywords: ["qubits", "quantum algorithms", "IBM Quantum", "quantum supremacy"],
        description: "Qubits, quantum algorithms, quantum supremacy",
    },

    // ── Career & Business ────────────────────────────────
    {
        id: "startups",
        name: "Startups",
        icon: "Rocket",
        category: "career",
        color: "from-amber-500 to-orange-500",
        accentColor: "#f59e0b",
        rssFeeds: [
            "https://techcrunch.com/feed/",
        ],
        searchKeywords: ["startups", "YC", "seed funding", "bootstrapping", "MVP"],
        description: "Founding, funding, scaling, YC",
    },
    {
        id: "vc-funding",
        name: "VC & Funding",
        icon: "CircleDollarSign",
        category: "career",
        color: "from-green-600 to-emerald-600",
        accentColor: "#16a34a",
        rssFeeds: [],
        searchKeywords: ["venture capital", "Series A", "angel investing", "fundraising"],
        description: "Venture capital, angel investing, fundraising",
    },
    {
        id: "product-management",
        name: "Product Management",
        icon: "Boxes",
        category: "career",
        color: "from-blue-500 to-cyan-500",
        accentColor: "#3b82f6",
        rssFeeds: [],
        searchKeywords: ["product strategy", "roadmapping", "user research", "agile"],
        description: "Product strategy, roadmaps, user research",
    },
    {
        id: "ux-design",
        name: "UX Design",
        icon: "Figma",
        category: "career",
        color: "from-pink-500 to-violet-500",
        accentColor: "#ec4899",
        rssFeeds: [],
        searchKeywords: ["UX", "UI design", "wireframing", "prototyping", "Figma"],
        description: "UI/UX, wireframing, prototyping",
    },
    {
        id: "marketing",
        name: "Marketing",
        icon: "Megaphone",
        category: "career",
        color: "from-yellow-500 to-orange-500",
        accentColor: "#eab308",
        rssFeeds: [],
        searchKeywords: ["digital marketing", "SEO", "content marketing", "growth hacking"],
        description: "Digital marketing, SEO, growth hacking",
    },
    {
        id: "finance",
        name: "Finance & Investing",
        icon: "Banknote",
        category: "career",
        color: "from-emerald-600 to-green-600",
        accentColor: "#059669",
        rssFeeds: [],
        searchKeywords: ["stock market", "investing", "portfolio", "fintech", "trading"],
        description: "Stock market, investing, fintech, trading",
    },

    // ── Sports & Fitness ─────────────────────────────────
    {
        id: "football",
        name: "Football (Soccer)",
        icon: "CircleDot",
        category: "sports",
        color: "from-green-500 to-emerald-500",
        accentColor: "#22c55e",
        rssFeeds: [
            "https://www.espn.com/espn/rss/soccer/news",
        ],
        searchKeywords: ["Premier League", "La Liga", "Champions League", "FIFA", "transfers"],
        description: "Premier League, La Liga, Champions League, transfers",
    },
    {
        id: "basketball",
        name: "Basketball",
        icon: "CircleDot",
        category: "sports",
        color: "from-orange-500 to-red-500",
        accentColor: "#f97316",
        rssFeeds: [],
        searchKeywords: ["NBA", "basketball", "March Madness", "draft", "scores"],
        description: "NBA, March Madness, draft picks, scores",
    },
    {
        id: "cricket",
        name: "Cricket",
        icon: "CircleDot",
        category: "sports",
        color: "from-blue-500 to-indigo-500",
        accentColor: "#3b82f6",
        rssFeeds: [
            "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
        ],
        searchKeywords: ["IPL", "ICC", "Test cricket", "World Cup", "T20"],
        description: "IPL, ICC, Test cricket, World Cup, T20",
    },
    {
        id: "tennis",
        name: "Tennis",
        icon: "CircleDot",
        category: "sports",
        color: "from-lime-500 to-green-500",
        accentColor: "#84cc16",
        rssFeeds: [],
        searchKeywords: ["ATP", "WTA", "Grand Slam", "Wimbledon", "US Open"],
        description: "Grand Slams, ATP/WTA tours, rankings",
    },
    {
        id: "formula1",
        name: "Formula 1",
        icon: "Car",
        category: "sports",
        color: "from-red-600 to-rose-600",
        accentColor: "#dc2626",
        rssFeeds: [],
        searchKeywords: ["F1", "Grand Prix", "Ferrari", "Red Bull Racing", "pit stop"],
        description: "Grand Prix, teams, drivers, tech",
    },
    {
        id: "esports",
        name: "Esports",
        icon: "Swords",
        category: "sports",
        color: "from-purple-600 to-fuchsia-600",
        accentColor: "#9333ea",
        rssFeeds: [],
        searchKeywords: ["Valorant", "League of Legends", "CS2", "Dota 2", "esports"],
        description: "Valorant, LoL, CS2, competitive gaming",
    },
    {
        id: "fitness",
        name: "Fitness & Gym",
        icon: "Dumbbell",
        category: "sports",
        color: "from-amber-500 to-orange-500",
        accentColor: "#f59e0b",
        rssFeeds: [],
        searchKeywords: ["workout", "bodybuilding", "crossfit", "strength training"],
        description: "Workouts, bodybuilding, strength training",
    },
    {
        id: "chess",
        name: "Chess",
        icon: "Crown",
        category: "sports",
        color: "from-stone-500 to-zinc-600",
        accentColor: "#78716c",
        rssFeeds: [],
        searchKeywords: ["chess", "Magnus Carlsen", "FIDE", "openings", "tactics"],
        description: "FIDE, grandmasters, openings, tactics",
    },

    // ── Creative Arts ────────────────────────────────────
    {
        id: "music-production",
        name: "Music Production",
        icon: "Music",
        category: "creative",
        color: "from-pink-500 to-rose-500",
        accentColor: "#ec4899",
        rssFeeds: [],
        searchKeywords: ["music production", "Ableton", "FL Studio", "mixing", "mastering"],
        description: "Ableton, FL Studio, mixing, mastering",
    },
    {
        id: "film-cinema",
        name: "Film & Cinema",
        icon: "Clapperboard",
        category: "creative",
        color: "from-yellow-600 to-amber-600",
        accentColor: "#ca8a04",
        rssFeeds: [],
        searchKeywords: ["movies", "filmmaking", "cinematography", "Oscars", "screenwriting"],
        description: "Filmmaking, cinematography, Oscars",
    },
    {
        id: "photography",
        name: "Photography",
        icon: "Camera",
        category: "creative",
        color: "from-gray-500 to-slate-600",
        accentColor: "#6b7280",
        rssFeeds: [],
        searchKeywords: ["photography techniques", "Lightroom", "portrait", "landscape"],
        description: "Techniques, editing, portrait, landscape",
    },
    {
        id: "graphic-design",
        name: "Graphic Design",
        icon: "Pen",
        category: "creative",
        color: "from-violet-500 to-purple-500",
        accentColor: "#8b5cf6",
        rssFeeds: [],
        searchKeywords: ["graphic design", "typography", "branding", "visual identity"],
        description: "Typography, branding, visual identity",
    },
    {
        id: "animation",
        name: "Animation",
        icon: "Film",
        category: "creative",
        color: "from-cyan-500 to-blue-500",
        accentColor: "#06b6d4",
        rssFeeds: [],
        searchKeywords: ["3D animation", "motion graphics", "Blender", "After Effects"],
        description: "3D, motion graphics, Blender",
    },
    {
        id: "fashion",
        name: "Fashion",
        icon: "Shirt",
        category: "creative",
        color: "from-rose-500 to-pink-500",
        accentColor: "#f43f5e",
        rssFeeds: [],
        searchKeywords: ["fashion trends", "streetwear", "haute couture", "sustainable fashion"],
        description: "Trends, streetwear, sustainable fashion",
    },

    // ── Lifestyle & Wellness ─────────────────────────────
    {
        id: "mental-health",
        name: "Mental Health",
        icon: "HeartPulse",
        category: "lifestyle",
        color: "from-violet-500 to-purple-500",
        accentColor: "#8b5cf6",
        rssFeeds: [],
        searchKeywords: ["anxiety", "mindfulness", "therapy", "self-care", "burnout"],
        description: "Mindfulness, therapy, self-care, burnout",
    },
    {
        id: "nutrition",
        name: "Nutrition",
        icon: "Apple",
        category: "lifestyle",
        color: "from-green-500 to-lime-500",
        accentColor: "#22c55e",
        rssFeeds: [],
        searchKeywords: ["diet", "macros", "meal prep", "supplements", "vitamins"],
        description: "Diet, macros, meal prep, supplements",
    },
    {
        id: "travel",
        name: "Travel",
        icon: "Plane",
        category: "lifestyle",
        color: "from-sky-500 to-cyan-500",
        accentColor: "#0ea5e9",
        rssFeeds: [],
        searchKeywords: ["travel tips", "backpacking", "budget travel", "digital nomad"],
        description: "Budget travel, backpacking, destinations",
    },
    {
        id: "personal-finance",
        name: "Personal Finance",
        icon: "Wallet",
        category: "lifestyle",
        color: "from-emerald-500 to-teal-500",
        accentColor: "#10b981",
        rssFeeds: [],
        searchKeywords: ["budgeting", "saving", "student loans", "credit score", "investing"],
        description: "Budgeting, saving, student loans, credit",
    },
    {
        id: "sustainability",
        name: "Sustainability",
        icon: "TreePine",
        category: "lifestyle",
        color: "from-green-600 to-emerald-600",
        accentColor: "#16a34a",
        rssFeeds: [],
        searchKeywords: ["zero waste", "eco-friendly", "carbon footprint", "green energy"],
        description: "Zero waste, eco-friendly, green living",
    },

    // ── Pop Culture ──────────────────────────────────────
    {
        id: "anime-manga",
        name: "Anime & Manga",
        icon: "Star",
        category: "popculture",
        color: "from-pink-500 to-red-500",
        accentColor: "#ec4899",
        rssFeeds: [],
        searchKeywords: ["anime", "manga", "shonen", "seasonal anime", "cosplay"],
        description: "Seasonal anime, manga, cosplay, fandom",
    },
    {
        id: "gaming",
        name: "Gaming",
        icon: "Gamepad2",
        category: "popculture",
        color: "from-green-500 to-cyan-500",
        accentColor: "#22c55e",
        rssFeeds: [],
        searchKeywords: ["gaming news", "PS5", "Xbox", "Nintendo", "PC gaming", "indie games"],
        description: "PC, console, indie, industry news",
    },
    {
        id: "memes",
        name: "Memes & Internet Culture",
        icon: "Laugh",
        category: "popculture",
        color: "from-yellow-500 to-amber-500",
        accentColor: "#eab308",
        rssFeeds: [],
        searchKeywords: ["memes", "viral", "internet culture", "Reddit", "TikTok trends"],
        description: "Viral trends, memes, internet humor",
    },
    {
        id: "streaming",
        name: "Streaming & Shows",
        icon: "Tv",
        category: "popculture",
        color: "from-red-600 to-rose-600",
        accentColor: "#dc2626",
        rssFeeds: [],
        searchKeywords: ["Netflix", "Disney+", "HBO", "TV shows", "binge-worthy"],
        description: "Netflix, Disney+, HBO, new releases",
    },
    {
        id: "kpop",
        name: "K-Pop & K-Culture",
        icon: "Sparkles",
        category: "popculture",
        color: "from-purple-500 to-pink-500",
        accentColor: "#a855f7",
        rssFeeds: [],
        searchKeywords: ["K-pop", "BTS", "BLACKPINK", "Korean drama", "K-beauty"],
        description: "K-pop groups, K-drama, Korean culture",
    },

    // ── Student Life ─────────────────────────────────────
    {
        id: "study-tips",
        name: "Study Tips",
        icon: "BookMarked",
        category: "studentlife",
        color: "from-sky-500 to-blue-500",
        accentColor: "#0ea5e9",
        rssFeeds: [],
        searchKeywords: ["study hacks", "Pomodoro", "note-taking", "active recall", "spaced repetition"],
        description: "Pomodoro, active recall, spaced repetition",
    },
    {
        id: "scholarships",
        name: "Scholarships",
        icon: "Award",
        category: "studentlife",
        color: "from-amber-500 to-yellow-500",
        accentColor: "#f59e0b",
        rssFeeds: [],
        searchKeywords: ["scholarships", "financial aid", "grants", "fellowships"],
        description: "Financial aid, grants, fellowships",
    },
    {
        id: "study-abroad",
        name: "Study Abroad",
        icon: "GlobeLock",
        category: "studentlife",
        color: "from-cyan-500 to-teal-500",
        accentColor: "#06b6d4",
        rssFeeds: [],
        searchKeywords: ["study abroad", "exchange programs", "visa", "IELTS", "GRE"],
        description: "Exchange programs, visa, IELTS, GRE",
    },
    {
        id: "resume-building",
        name: "Resume Building",
        icon: "FileText",
        category: "studentlife",
        color: "from-indigo-500 to-blue-500",
        accentColor: "#6366f1",
        rssFeeds: [],
        searchKeywords: ["resume", "CV", "cover letter", "ATS", "portfolio"],
        description: "CV, cover letters, ATS optimization",
    },
    {
        id: "interview-prep",
        name: "Interview Prep",
        icon: "MessageSquare",
        category: "studentlife",
        color: "from-violet-500 to-indigo-500",
        accentColor: "#8b5cf6",
        rssFeeds: [],
        searchKeywords: ["job interview", "coding interview", "behavioral questions", "LeetCode"],
        description: "Coding interviews, behavioral, LeetCode",
    },
    {
        id: "hackathons",
        name: "Hackathons",
        icon: "Code",
        category: "studentlife",
        color: "from-cyan-600 to-blue-600",
        accentColor: "#0891b2",
        rssFeeds: [],
        searchKeywords: ["hackathon", "MLH", "devpost", "coding competition"],
        description: "MLH, Devpost, coding competitions",
    },
];

// Helper: get domains by category
export function getDomainsByCategory(category: DomainCategory): DomainDef[] {
    return DOMAINS.filter((d) => d.category === category);
}

// Helper: get a domain by ID
export function getDomainById(id: string): DomainDef | undefined {
    return DOMAINS.find((d) => d.id === id);
}
